export const mockClients = [
  {
    id: '1',
    name: 'Wanjiku Kamau',
    phone: '+254 712 345 678',
    email: 'wanjiku.k@gmail.com',
    lastVisit: '2025-11-10',
    totalVisits: 24,
    totalSpent: 285000,
    loyaltyPoints: 285,
    birthday: '1990-05-15',
    notes: 'Prefers natural products, allergic to sulfates',
    favoriteServices: ['Balayage', 'Deep Conditioning'],
    preferredStaff: 'Akinyi Odhiambo',
    photo: null
  },
  {
    id: '2',
    name: 'Brian Kipchoge',
    phone: '+254 722 456 789',
    email: 'bkipchoge@gmail.com',
    lastVisit: '2025-11-08',
    totalVisits: 15,
    totalSpent: 120000,
    loyaltyPoints: 120,
    birthday: '1985-08-22',
    notes: 'Prefers short appointments',
    favoriteServices: ['Haircut', 'Beard Trim'],
    preferredStaff: 'James Mwangi',
    photo: null
  },
  {
    id: '3',
    name: 'Amina Hassan',
    phone: '+254 733 567 890',
    email: 'amina.hassan@gmail.com',
    lastVisit: '2025-11-05',
    totalVisits: 32,
    totalSpent: 410000,
    loyaltyPoints: 410,
    birthday: '1992-03-10',
    notes: 'VIP client, loves trying new styles',
    favoriteServices: ['Color Treatment', 'Keratin Treatment'],
    preferredStaff: 'Akinyi Odhiambo',
    photo: null
  },
  {
    id: '4',
    name: 'David Omondi',
    phone: '+254 744 678 901',
    email: 'david.omondi@gmail.com',
    lastVisit: '2025-11-12',
    totalVisits: 8,
    totalSpent: 68000,
    loyaltyPoints: 68,
    birthday: '1988-11-30',
    notes: '',
    favoriteServices: ['Haircut'],
    preferredStaff: 'James Mwangi',
    photo: null
  },
  {
    id: '5',
    name: 'Faith Njeri',
    phone: '+254 755 789 012',
    email: 'faith.njeri@gmail.com',
    lastVisit: '2025-11-11',
    totalVisits: 19,
    totalSpent: 220000,
    loyaltyPoints: 220,
    birthday: '1995-07-18',
    notes: 'Bridal client',
    favoriteServices: ['Updo', 'Makeup'],
    preferredStaff: 'Mercy Wangari',
    photo: null
  },
  {
    id: '6',
    name: 'Kevin Mutua',
    phone: '+254 700 123 456',
    email: 'k.mutua@yahoo.com',
    lastVisit: '2025-11-09',
    totalVisits: 12,
    totalSpent: 96000,
    loyaltyPoints: 96,
    birthday: '1993-02-20',
    notes: 'Prefers afternoon appointments',
    favoriteServices: ['Haircut - Men', 'Hair Wash'],
    preferredStaff: 'James Mwangi',
    photo: null
  },
  {
    id: '7',
    name: 'Halima Abdi',
    phone: '+254 711 234 567',
    email: 'halima.abdi@gmail.com',
    lastVisit: '2025-11-07',
    totalVisits: 28,
    totalSpent: 336000,
    loyaltyPoints: 336,
    birthday: '1987-09-14',
    notes: 'Prefers hijab-friendly services',
    favoriteServices: ['Manicure', 'Pedicure', 'Henna'],
    preferredStaff: 'Mercy Wangari',
    photo: null
  },
  {
    id: '8',
    name: 'Dennis Otieno',
    phone: '+254 723 345 678',
    email: 'dennis.otieno@gmail.com',
    lastVisit: '2025-11-13',
    totalVisits: 6,
    totalSpent: 48000,
    loyaltyPoints: 48,
    birthday: '1996-12-05',
    notes: 'Student, often books during holidays',
    favoriteServices: ['Haircut - Men'],
    preferredStaff: 'James Mwangi',
    photo: null
  },
  {
    id: '9',
    name: 'Njoki Kariuki',
    phone: '+254 734 456 789',
    email: 'njoki.k@outlook.com',
    lastVisit: '2025-11-06',
    totalVisits: 18,
    totalSpent: 234000,
    loyaltyPoints: 234,
    birthday: '1991-06-28',
    notes: 'Corporate client, books monthly',
    favoriteServices: ['Silk Press', 'Deep Conditioning'],
    preferredStaff: 'Akinyi Odhiambo',
    photo: null
  },
  {
    id: '10',
    name: 'Peter Kiprotich',
    phone: '+254 745 567 890',
    email: 'p.kiprotich@gmail.com',
    lastVisit: '2025-11-11',
    totalVisits: 10,
    totalSpent: 80000,
    loyaltyPoints: 80,
    birthday: '1989-04-17',
    notes: '',
    favoriteServices: ['Haircut - Men', 'Beard Styling'],
    preferredStaff: 'James Mwangi',
    photo: null
  }
];

export const mockServices = [
  {
    id: '1',
    name: 'Haircut - Women',
    category: 'Hair',
    price: 1500,
    duration: 45,
    description: 'Professional haircut and styling',
    active: true,
    photo: null
  },
  {
    id: '2',
    name: 'Haircut - Men',
    category: 'Hair',
    price: 800,
    duration: 30,
    description: 'Classic or modern haircut',
    active: true,
    photo: null
  },
  {
    id: '3',
    name: 'Balayage',
    category: 'Hair',
    price: 12000,
    duration: 180,
    description: 'Hand-painted highlights for natural look',
    active: true,
    photo: null
  },
  {
    id: '4',
    name: 'Color Treatment',
    category: 'Hair',
    price: 8000,
    duration: 120,
    description: 'Full color application',
    active: true,
    photo: null
  },
  {
    id: '5',
    name: 'Keratin Treatment',
    category: 'Hair',
    price: 15000,
    duration: 150,
    description: 'Smoothing treatment for frizz-free hair',
    active: true,
    photo: null
  },
  {
    id: '6',
    name: 'Deep Conditioning',
    category: 'Hair',
    price: 2500,
    duration: 30,
    description: 'Intensive moisture treatment',
    active: true,
    photo: null
  },
  {
    id: '7',
    name: 'Manicure',
    category: 'Nails',
    price: 1000,
    duration: 45,
    description: 'Classic manicure with polish',
    active: true,
    photo: null
  },
  {
    id: '8',
    name: 'Gel Nails',
    category: 'Nails',
    price: 2500,
    duration: 60,
    description: 'Long-lasting gel polish',
    active: true,
    photo: null
  },
  {
    id: '9',
    name: 'Facial Treatment',
    category: 'Spa',
    price: 3500,
    duration: 60,
    description: 'Relaxing facial with skin analysis',
    active: true,
    photo: null
  },
  {
    id: '10',
    name: 'Massage',
    category: 'Spa',
    price: 4000,
    duration: 60,
    description: 'Full body relaxation massage',
    active: true,
    photo: null
  },
  {
    id: '11',
    name: 'Braids - Box Braids',
    category: 'Hair',
    price: 3500,
    duration: 240,
    description: 'Classic box braids styling',
    active: true,
    photo: null
  },
  {
    id: '12',
    name: 'Weaving',
    category: 'Hair',
    price: 2500,
    duration: 120,
    description: 'Hair weave installation',
    active: true,
    photo: null
  },
  {
    id: '13',
    name: 'Dreadlocks Maintenance',
    category: 'Hair',
    price: 2000,
    duration: 90,
    description: 'Dreadlock retwist and maintenance',
    active: true,
    photo: null
  },
  {
    id: '14',
    name: 'Pedicure',
    category: 'Nails',
    price: 1200,
    duration: 45,
    description: 'Foot care and polish',
    active: true,
    photo: null
  },
  {
    id: '15',
    name: 'Beard Trim & Styling',
    category: 'Hair',
    price: 500,
    duration: 20,
    description: 'Professional beard grooming',
    active: true,
    photo: null
  },
  {
    id: '16',
    name: 'Hair Wash & Blow Dry',
    category: 'Hair',
    price: 1000,
    duration: 30,
    description: 'Shampoo, condition and blow dry',
    active: true,
    photo: null
  },
  {
    id: '17',
    name: 'Silk Press',
    category: 'Hair',
    price: 3000,
    duration: 120,
    description: 'Straightening treatment with silk finish',
    active: true,
    photo: null
  },
  {
    id: '18',
    name: 'Makeup - Full Face',
    category: 'Makeup',
    price: 3500,
    duration: 60,
    description: 'Professional makeup application',
    active: true,
    photo: null
  },
  {
    id: '19',
    name: 'Bridal Package',
    category: 'Special',
    price: 25000,
    duration: 300,
    description: 'Complete bridal hair and makeup',
    active: true,
    photo: null
  },
  {
    id: '20',
    name: 'Henna Application',
    category: 'Special',
    price: 1500,
    duration: 45,
    description: 'Natural henna design',
    active: true,
    photo: null
  }
];

export const mockStaff = [
  {
    id: '1',
    name: 'Akinyi Odhiambo',
    role: 'Senior Stylist',
    phone: '+254 720 111 222',
    email: 'akinyi@luxesalon.co.ke',
    rating: 4.9,
    totalBookings: 1250,
    commissionRate: 40,
    workingHours: '9:00 AM - 6:00 PM',
    daysOff: ['Sunday', 'Monday'],
    services: ['Haircut', 'Balayage', 'Color Treatment', 'Keratin Treatment', 'Silk Press'],
    photo: null
  },
  {
    id: '2',
    name: 'James Mwangi',
    role: 'Master Barber',
    phone: '+254 721 222 333',
    email: 'james.m@luxesalon.co.ke',
    rating: 4.8,
    totalBookings: 980,
    commissionRate: 35,
    workingHours: '10:00 AM - 7:00 PM',
    daysOff: ['Sunday'],
    services: ['Haircut - Men', 'Beard Trim & Styling', 'Dreadlocks Maintenance'],
    photo: null
  },
  {
    id: '3',
    name: 'Mercy Wangari',
    role: 'Nail Technician & Beautician',
    phone: '+254 722 333 444',
    email: 'mercy.w@luxesalon.co.ke',
    rating: 5.0,
    totalBookings: 1100,
    commissionRate: 40,
    workingHours: '9:00 AM - 5:00 PM',
    daysOff: ['Monday'],
    services: ['Manicure', 'Gel Nails', 'Pedicure', 'Makeup - Full Face', 'Henna Application'],
    photo: null
  },
  {
    id: '4',
    name: 'Zawadi Muthoni',
    role: 'Spa Therapist',
    phone: '+254 723 444 555',
    email: 'zawadi.m@luxesalon.co.ke',
    rating: 4.9,
    totalBookings: 850,
    commissionRate: 45,
    workingHours: '10:00 AM - 6:00 PM',
    daysOff: ['Sunday', 'Wednesday'],
    services: ['Facial Treatment', 'Massage'],
    photo: null
  },
  {
    id: '5',
    name: 'Fatuma Abdi',
    role: 'Hair Stylist',
    phone: '+254 724 555 666',
    email: 'fatuma.a@luxesalon.co.ke',
    rating: 4.8,
    totalBookings: 920,
    commissionRate: 38,
    workingHours: '9:00 AM - 6:00 PM',
    daysOff: ['Sunday', 'Tuesday'],
    services: ['Braids - Box Braids', 'Weaving', 'Hair Wash & Blow Dry', 'Deep Conditioning'],
    photo: null
  },
  {
    id: '6',
    name: 'Collins Otieno',
    role: 'Junior Stylist',
    phone: '+254 725 666 777',
    email: 'collins.o@luxesalon.co.ke',
    rating: 4.6,
    totalBookings: 450,
    commissionRate: 30,
    workingHours: '10:00 AM - 7:00 PM',
    daysOff: ['Monday', 'Tuesday'],
    services: ['Haircut - Men', 'Haircut - Women', 'Hair Wash & Blow Dry'],
    photo: null
  }
];

export const mockAppointments = [
  {
    id: '1',
    clientId: '1',
    clientName: 'Wanjiku Kamau',
    staffId: '1',
    staffName: 'Akinyi Odhiambo',
    serviceId: '3',
    serviceName: 'Balayage',
    date: '2025-11-15',
    time: '10:00 AM',
    duration: 180,
    price: 12000,
    status: 'confirmed',
    paymentStatus: 'paid',
    notes: '',
    smsReminder: true
  },
  {
    id: '2',
    clientId: '4',
    clientName: 'David Omondi',
    staffId: '2',
    staffName: 'James Mwangi',
    serviceId: '2',
    serviceName: 'Haircut - Men',
    date: '2025-11-15',
    time: '11:00 AM',
    duration: 30,
    price: 800,
    status: 'confirmed',
    paymentStatus: 'unpaid',
    notes: '',
    smsReminder: true
  },
  {
    id: '3',
    clientId: '3',
    clientName: 'Amina Hassan',
    staffId: '3',
    staffName: 'Mercy Wangari',
    serviceId: '8',
    serviceName: 'Gel Nails',
    date: '2025-11-15',
    time: '2:00 PM',
    duration: 60,
    price: 2500,
    status: 'pending',
    paymentStatus: 'unpaid',
    notes: 'Requested pink color',
    smsReminder: false
  },
  {
    id: '4',
    clientId: '2',
    clientName: 'Brian Kipchoge',
    staffId: '2',
    staffName: 'James Mwangi',
    serviceId: '2',
    serviceName: 'Haircut - Men',
    date: '2025-11-15',
    time: '3:30 PM',
    duration: 30,
    price: 800,
    status: 'confirmed',
    paymentStatus: 'deposit',
    notes: '',
    smsReminder: true
  },
  {
    id: '5',
    clientId: '1',
    clientName: 'Wanjiku Kamau',
    staffId: '4',
    staffName: 'Zawadi Muthoni',
    serviceId: '9',
    serviceName: 'Facial Treatment',
    date: '2025-11-16',
    time: '10:00 AM',
    duration: 60,
    price: 3500,
    status: 'confirmed',
    paymentStatus: 'unpaid',
    notes: '',
    smsReminder: true
  },
  {
    id: '6',
    clientId: '5',
    clientName: 'Faith Njeri',
    staffId: '3',
    staffName: 'Mercy Wangari',
    serviceId: '18',
    serviceName: 'Makeup - Full Face',
    date: '2025-11-15',
    time: '9:00 AM',
    duration: 60,
    price: 3500,
    status: 'confirmed',
    paymentStatus: 'paid',
    notes: 'Event makeup',
    smsReminder: true
  },
  {
    id: '7',
    clientId: '7',
    clientName: 'Halima Abdi',
    staffId: '3',
    staffName: 'Mercy Wangari',
    serviceId: '7',
    serviceName: 'Manicure',
    date: '2025-11-15',
    time: '4:30 PM',
    duration: 45,
    price: 1000,
    status: 'pending',
    paymentStatus: 'unpaid',
    notes: '',
    smsReminder: true
  },
  {
    id: '8',
    clientId: '9',
    clientName: 'Njoki Kariuki',
    staffId: '1',
    staffName: 'Akinyi Odhiambo',
    serviceId: '17',
    serviceName: 'Silk Press',
    date: '2025-11-16',
    time: '11:30 AM',
    duration: 120,
    price: 3000,
    status: 'confirmed',
    paymentStatus: 'deposit',
    notes: 'Corporate event prep',
    smsReminder: true
  },
  {
    id: '9',
    clientId: '10',
    clientName: 'Peter Kiprotich',
    staffId: '2',
    staffName: 'James Mwangi',
    serviceId: '15',
    serviceName: 'Beard Trim & Styling',
    date: '2025-11-15',
    time: '1:00 PM',
    duration: 20,
    price: 500,
    status: 'confirmed',
    paymentStatus: 'unpaid',
    notes: '',
    smsReminder: false
  },
  {
    id: '10',
    clientId: '6',
    clientName: 'Kevin Mutua',
    staffId: '2',
    staffName: 'James Mwangi',
    serviceId: '2',
    serviceName: 'Haircut - Men',
    date: '2025-11-16',
    time: '3:00 PM',
    duration: 30,
    price: 800,
    status: 'pending',
    paymentStatus: 'unpaid',
    notes: 'Prefers fade cut',
    smsReminder: true
  }
];

export const mockInventory = [
  {
    id: '1',
    name: 'Shampoo - Moisturizing (Dark & Lovely)',
    category: 'Hair Care',
    stock: 15,
    minStock: 10,
    unit: 'bottles',
    lastRestocked: '2025-11-01'
  },
  {
    id: '2',
    name: 'Hair Relaxer (Olive Oil)',
    category: 'Chemical',
    stock: 8,
    minStock: 12,
    unit: 'boxes',
    lastRestocked: '2025-10-28'
  },
  {
    id: '3',
    name: 'Braiding Hair - Synthetic',
    category: 'Extensions',
    stock: 25,
    minStock: 20,
    unit: 'packs',
    lastRestocked: '2025-11-10'
  },
  {
    id: '4',
    name: 'Nail Polish - OPI Red',
    category: 'Nails',
    stock: 3,
    minStock: 5,
    unit: 'bottles',
    lastRestocked: '2025-10-25'
  },
  {
    id: '5',
    name: 'Face Mask - Hydrating',
    category: 'Spa',
    stock: 20,
    minStock: 12,
    unit: 'units',
    lastRestocked: '2025-11-05'
  },
  {
    id: '6',
    name: 'Hair Color - Black',
    category: 'Color',
    stock: 12,
    minStock: 8,
    unit: 'tubes',
    lastRestocked: '2025-11-08'
  },
  {
    id: '7',
    name: 'Coconut Oil - Organic',
    category: 'Hair Care',
    stock: 10,
    minStock: 8,
    unit: 'bottles',
    lastRestocked: '2025-11-02'
  },
  {
    id: '8',
    name: 'Gel Nail Polish Set',
    category: 'Nails',
    stock: 18,
    minStock: 15,
    unit: 'sets',
    lastRestocked: '2025-11-09'
  },
  {
    id: '9',
    name: 'Henna Powder - Natural',
    category: 'Special',
    stock: 6,
    minStock: 5,
    unit: 'packs',
    lastRestocked: '2025-11-03'
  },
  {
    id: '10',
    name: 'Beard Oil - Argan',
    category: 'Grooming',
    stock: 7,
    minStock: 5,
    unit: 'bottles',
    lastRestocked: '2025-11-06'
  }
];

export const mockRevenueData = [
  { day: 'Mon', revenue: 45000 },
  { day: 'Tue', revenue: 68000 },
  { day: 'Wed', revenue: 52000 },
  { day: 'Thu', revenue: 78000 },
  { day: 'Fri', revenue: 95000 },
  { day: 'Sat', revenue: 125000 },
  { day: 'Sun', revenue: 85000 }
];